### PR TITLE
Include height field in the site-editor

### PR DESCRIPTION
**Pull request by lucvysk**
#### What problem is this solving?

Hi team! In order to improve CLS score in the page, images needs to have the height attribute. Currently we have an experimental prop which allow that to happens, however the prod of `height` doesn't appears in the site editor and once the component is changed (throught the site-editor) the prop `height` is overwritten and starts to be blank - by passing what was defined in the theme.

#### How to test it?

https://vysk2--hunterdouglasnl.myvtex.com/

#### Screenshots or example usage:

image

image

image

### CODE REVIEW

**Review by vsseixaso — DISMISSED** [review]

**Review by sheilagomes — APPROVED** [review]
LGTM

**Comment by vsseixaso** [comment]
@lucvysk , it is necessary to add the prop description in [README.md](https://github.com/vtex-apps/store-image?tab=readme-ov-file#image-list-props)

**Comment by Maik3345** [comment]
hi @lucvysk, Wouldn't it be good to also be able to define the use of width and height for the mobile version? When you define the width and use the image on mobile it is deformed because the size is forced when using these props

We pass the height and width 
image


But in mobile this deform the imagen

image

**Comment by lucvysk** [comment]
> @lucvysk , it is necessary to add the prop description in [README.md](https://github.com/vtex-apps/store-image?tab=readme-ov-file#image-list-props)

@vsseixaso The prop is in the readme but it wasn't replicated in the site-editor: https://github.com/vtex-apps/store-image/blob/master/docs/README.md#list-contextimage-list-props

**Comment by lucvysk** [comment]
> hi @lucvysk, Wouldn't it be good to also be able to define the use of width and height for the mobile version? When you define the width and use the image on mobile it is deformed because the size is forced when using these props
> 
> We pass the height and width image
> 
> But in mobile this deform the imagen
> 
> image

@Maik3345 The idea is mostly to increase performance score in Google. It mostly minds if the field is missing and thinking about responsiveness, size in mobile can and **should** be handled through css. Even if we are looking for something further, it can be a next feature request. (as WiP)

**Comment by Maik3345** [comment]
> > hi @lucvysk, Wouldn't it be good to also be able to define the use of width and height for the mobile version? When you define the width and use the image on mobile it is deformed because the size is forced when using these props
> > We pass the height and width image
> > But in mobile this deform the imagen
> > image
> 
> @Maik3345 The idea is mostly to increase performance score in Google. It mostly minds if the field is missing and thinking about responsiveness, size in mobile can and **should** be handled through css. Even if we are looking for something further, it can be a next feature request. (as WiP)

@lucvysk Thanks for the information!

**Review by vsseixaso — APPROVED** [review]

**Comment by Maik3345** [comment]
@lucvysk  this change make errors in some stores. this malform the image of the banners and is necesary the intervention from the site editor to fix it. 

https://tiendaonline.puntoscolombia.com/ --> this is my case, to fix it i need go to the site editor and pass the height to all image list in the home or a landing pages. 

image
I need go to the site editor and pass the height in the image list to fix it

**Comment by ivanlopezluna** [comment]
@lucvysk 
This change is causing images to appear distorted in several stores that are already in production. Although it can be corrected by assigning a `height: auto !important`, this will have to be done in each of the stores.

**Comment by felipealmeidacorrea** [comment]
@vsseixaso @lucvysk this changes is causing images to appear distorted when they are in image lists. Looks like it's happening because the heigh prop of the list-context.image-list is being set as the height prop for the entire list elements

**Pull request merged**
